### ISSUE TITLE
老哥为啥运行不了啊

### ISSUE THREAD

**Issue by ACTony47** [Limaomao821/selfmade_CPU#1]

**Comment by Limaomao821** [comment]
> _No description provided._
你好，在我开始学习计算机体系结构的时候，我建立了这个仓库来保存一些练习性质的代码。
这个仓库支持的指令数目十分有限，不具有太大的学习价值。
建议参考[自己动手写CPU](https://book.douban.com/subject/25960657/)来学习。
btw，我当时的运行环境是ubuntu + iverilog + gtkwave。

**Comment by ACTony47** [comment]
好的，谢谢
